import "./globals.css";
import type { Metadata } from "next";
import { Lora } from "next/font/google";
import { ReduxProvider } from "./redux/provider";
import Head from "next/head";

const inter = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VNV solutions ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
      </Head>
      <html lang="uk">
        <ReduxProvider>
          <body className={inter.className}>{children}</body>
        </ReduxProvider>
      </html>
    </>
  );
}
