import "./globals.css";
import { Metadata } from "next";
import { Lora } from "next/font/google";
import { ReduxProvider } from "./redux/provider";

const inter = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VNV solutions ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="uk">
        <ReduxProvider>
          <body className={inter.className}>{children}</body>
        </ReduxProvider>
      </html>
    </>
  );
}
